### PR TITLE
History deforked

### PR DESCRIPTION
**Pull request by eyalliebermann**
reintroducing 
commit 50cefa845830412efc241db9194040ff6616cf93
Author: galvinograd <gal.vinograd@gmail.com>
Date:   Tue Aug 1 02:35:00 2017 +0300

    eslint, travis and logs

### CODE REVIEW

**Comment by galvinograd** [comment]
It's a cool idea, I liked the implementation's simplicity. :)
Though I have a few problems with this feature:

1. We have only 3 active messages at the time, there are more filters than messages in the system. I think this feature is way premature.
2. It does not handle the most important aspect of filtering - the notifications :)
3. Since we'll have 9 more filters (Moshe's fields of interest), we would need to implement it as a multi select box (maybe in a different screen with TabNavigator?).

What do you think?

**Comment by eyalliebermann** [comment]
I agree
Filtering notifications is critical
The other filters can be added gradually
And you have not mentioned the positioning issue stuff

If you think it's premature I'd pull back the feature, and yet I'd like the history unification.
That's the main purpose of this request.
The feature is reintroduced as a side effect.
I'll take it down on a commit in a minute

**Comment by galvinograd** [comment]
There are still change leftovers at App/js/MessagesScreen.js :)
But sure, sounds great

**Comment by galvinograd** [comment]
There are still left over changes (you can just git revert or git rebase -i to remove all of them). The build will fail because of them.

**Comment by eyalliebermann** [comment]
re lint changes made
please update the README file regarding pull-request process
naming conventions of branches
running the lint
etc

**Pull request merged**
